// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packagehello.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_packagehello_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_packagehello_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_packagehello_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_packagehello_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_packagehello_2eproto;
namespace streamout {
namespace v1 {
class HelloReply;
struct HelloReplyDefaultTypeInternal;
extern HelloReplyDefaultTypeInternal _HelloReply_default_instance_;
class HelloRequest;
struct HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
class StreamoutActionResponse;
struct StreamoutActionResponseDefaultTypeInternal;
extern StreamoutActionResponseDefaultTypeInternal _StreamoutActionResponse_default_instance_;
class StreamoutDebugRequest;
struct StreamoutDebugRequestDefaultTypeInternal;
extern StreamoutDebugRequestDefaultTypeInternal _StreamoutDebugRequest_default_instance_;
class StreamoutSetPipelineRequest;
struct StreamoutSetPipelineRequestDefaultTypeInternal;
extern StreamoutSetPipelineRequestDefaultTypeInternal _StreamoutSetPipelineRequest_default_instance_;
class StreamoutSetPortRequest;
struct StreamoutSetPortRequestDefaultTypeInternal;
extern StreamoutSetPortRequestDefaultTypeInternal _StreamoutSetPortRequest_default_instance_;
class StreamoutSetProductIdRequest;
struct StreamoutSetProductIdRequestDefaultTypeInternal;
extern StreamoutSetProductIdRequestDefaultTypeInternal _StreamoutSetProductIdRequest_default_instance_;
class StreamoutStartRequest;
struct StreamoutStartRequestDefaultTypeInternal;
extern StreamoutStartRequestDefaultTypeInternal _StreamoutStartRequest_default_instance_;
class StreamoutStatusRequest;
struct StreamoutStatusRequestDefaultTypeInternal;
extern StreamoutStatusRequestDefaultTypeInternal _StreamoutStatusRequest_default_instance_;
class StreamoutStatusResponse;
struct StreamoutStatusResponseDefaultTypeInternal;
extern StreamoutStatusResponseDefaultTypeInternal _StreamoutStatusResponse_default_instance_;
class StreamoutStopRequest;
struct StreamoutStopRequestDefaultTypeInternal;
extern StreamoutStopRequestDefaultTypeInternal _StreamoutStopRequest_default_instance_;
}  // namespace v1
}  // namespace streamout
PROTOBUF_NAMESPACE_OPEN
template<> ::streamout::v1::HelloReply* Arena::CreateMaybeMessage<::streamout::v1::HelloReply>(Arena*);
template<> ::streamout::v1::HelloRequest* Arena::CreateMaybeMessage<::streamout::v1::HelloRequest>(Arena*);
template<> ::streamout::v1::StreamoutActionResponse* Arena::CreateMaybeMessage<::streamout::v1::StreamoutActionResponse>(Arena*);
template<> ::streamout::v1::StreamoutDebugRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutDebugRequest>(Arena*);
template<> ::streamout::v1::StreamoutSetPipelineRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutSetPipelineRequest>(Arena*);
template<> ::streamout::v1::StreamoutSetPortRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutSetPortRequest>(Arena*);
template<> ::streamout::v1::StreamoutSetProductIdRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutSetProductIdRequest>(Arena*);
template<> ::streamout::v1::StreamoutStartRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutStartRequest>(Arena*);
template<> ::streamout::v1::StreamoutStatusRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutStatusRequest>(Arena*);
template<> ::streamout::v1::StreamoutStatusResponse* Arena::CreateMaybeMessage<::streamout::v1::StreamoutStatusResponse>(Arena*);
template<> ::streamout::v1::StreamoutStopRequest* Arena::CreateMaybeMessage<::streamout::v1::StreamoutStopRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace streamout {
namespace v1 {

enum StreamStatus : int {
  STREAM_STATUS_UNSPECIFIED = 0,
  STREAM_STATUS_READY = 1,
  STREAM_STATUS_CLIENT_CONNECTED = 2,
  STREAM_STATUS_STOPPED = 3,
  StreamStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  StreamStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool StreamStatus_IsValid(int value);
constexpr StreamStatus StreamStatus_MIN = STREAM_STATUS_UNSPECIFIED;
constexpr StreamStatus StreamStatus_MAX = STREAM_STATUS_STOPPED;
constexpr int StreamStatus_ARRAYSIZE = StreamStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StreamStatus_descriptor();
template<typename T>
inline const std::string& StreamStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, StreamStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function StreamStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    StreamStatus_descriptor(), enum_t_value);
}
inline bool StreamStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, StreamStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<StreamStatus>(
    StreamStatus_descriptor(), name, value);
}
// ===================================================================

class HelloRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.HelloRequest) */ {
 public:
  inline HelloRequest() : HelloRequest(nullptr) {}
  ~HelloRequest() override;
  explicit PROTOBUF_CONSTEXPR HelloRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HelloRequest(const HelloRequest& from);
  HelloRequest(HelloRequest&& from) noexcept
    : HelloRequest() {
    *this = ::std::move(from);
  }

  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloRequest& operator=(HelloRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HelloRequest* internal_default_instance() {
    return reinterpret_cast<const HelloRequest*>(
               &_HelloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HelloRequest& a, HelloRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HelloRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HelloRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HelloRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HelloRequest& from) {
    HelloRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.HelloRequest";
  }
  protected:
  explicit HelloRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.HelloRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class HelloReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.HelloReply) */ {
 public:
  inline HelloReply() : HelloReply(nullptr) {}
  ~HelloReply() override;
  explicit PROTOBUF_CONSTEXPR HelloReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HelloReply(const HelloReply& from);
  HelloReply(HelloReply&& from) noexcept
    : HelloReply() {
    *this = ::std::move(from);
  }

  inline HelloReply& operator=(const HelloReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloReply& operator=(HelloReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const HelloReply* internal_default_instance() {
    return reinterpret_cast<const HelloReply*>(
               &_HelloReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HelloReply& a, HelloReply& b) {
    a.Swap(&b);
  }
  inline void Swap(HelloReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HelloReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HelloReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HelloReply& from) {
    HelloReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.HelloReply";
  }
  protected:
  explicit HelloReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.HelloReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutSetPortRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutSetPortRequest) */ {
 public:
  inline StreamoutSetPortRequest() : StreamoutSetPortRequest(nullptr) {}
  ~StreamoutSetPortRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutSetPortRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutSetPortRequest(const StreamoutSetPortRequest& from);
  StreamoutSetPortRequest(StreamoutSetPortRequest&& from) noexcept
    : StreamoutSetPortRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutSetPortRequest& operator=(const StreamoutSetPortRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutSetPortRequest& operator=(StreamoutSetPortRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutSetPortRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutSetPortRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutSetPortRequest*>(
               &_StreamoutSetPortRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StreamoutSetPortRequest& a, StreamoutSetPortRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutSetPortRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutSetPortRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutSetPortRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutSetPortRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutSetPortRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutSetPortRequest& from) {
    StreamoutSetPortRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutSetPortRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutSetPortRequest";
  }
  protected:
  explicit StreamoutSetPortRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPortFieldNumber = 1,
  };
  // string port = 1;
  void clear_port();
  const std::string& port() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_port(ArgT0&& arg0, ArgT... args);
  std::string* mutable_port();
  PROTOBUF_NODISCARD std::string* release_port();
  void set_allocated_port(std::string* port);
  private:
  const std::string& _internal_port() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_port(const std::string& value);
  std::string* _internal_mutable_port();
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutSetPortRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutSetPipelineRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutSetPipelineRequest) */ {
 public:
  inline StreamoutSetPipelineRequest() : StreamoutSetPipelineRequest(nullptr) {}
  ~StreamoutSetPipelineRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutSetPipelineRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutSetPipelineRequest(const StreamoutSetPipelineRequest& from);
  StreamoutSetPipelineRequest(StreamoutSetPipelineRequest&& from) noexcept
    : StreamoutSetPipelineRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutSetPipelineRequest& operator=(const StreamoutSetPipelineRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutSetPipelineRequest& operator=(StreamoutSetPipelineRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutSetPipelineRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutSetPipelineRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutSetPipelineRequest*>(
               &_StreamoutSetPipelineRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(StreamoutSetPipelineRequest& a, StreamoutSetPipelineRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutSetPipelineRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutSetPipelineRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutSetPipelineRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutSetPipelineRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutSetPipelineRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutSetPipelineRequest& from) {
    StreamoutSetPipelineRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutSetPipelineRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutSetPipelineRequest";
  }
  protected:
  explicit StreamoutSetPipelineRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPipelineFieldNumber = 1,
  };
  // string pipeline = 1;
  void clear_pipeline();
  const std::string& pipeline() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pipeline(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pipeline();
  PROTOBUF_NODISCARD std::string* release_pipeline();
  void set_allocated_pipeline(std::string* pipeline);
  private:
  const std::string& _internal_pipeline() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pipeline(const std::string& value);
  std::string* _internal_mutable_pipeline();
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutSetPipelineRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pipeline_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutDebugRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutDebugRequest) */ {
 public:
  inline StreamoutDebugRequest() : StreamoutDebugRequest(nullptr) {}
  ~StreamoutDebugRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutDebugRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutDebugRequest(const StreamoutDebugRequest& from);
  StreamoutDebugRequest(StreamoutDebugRequest&& from) noexcept
    : StreamoutDebugRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutDebugRequest& operator=(const StreamoutDebugRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutDebugRequest& operator=(StreamoutDebugRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutDebugRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutDebugRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutDebugRequest*>(
               &_StreamoutDebugRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StreamoutDebugRequest& a, StreamoutDebugRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutDebugRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutDebugRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutDebugRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutDebugRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutDebugRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutDebugRequest& from) {
    StreamoutDebugRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutDebugRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutDebugRequest";
  }
  protected:
  explicit StreamoutDebugRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDebugStringFieldNumber = 1,
  };
  // string debug_string = 1;
  void clear_debug_string();
  const std::string& debug_string() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_debug_string(ArgT0&& arg0, ArgT... args);
  std::string* mutable_debug_string();
  PROTOBUF_NODISCARD std::string* release_debug_string();
  void set_allocated_debug_string(std::string* debug_string);
  private:
  const std::string& _internal_debug_string() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_debug_string(const std::string& value);
  std::string* _internal_mutable_debug_string();
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutDebugRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr debug_string_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutStartRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutStartRequest) */ {
 public:
  inline StreamoutStartRequest() : StreamoutStartRequest(nullptr) {}
  ~StreamoutStartRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutStartRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutStartRequest(const StreamoutStartRequest& from);
  StreamoutStartRequest(StreamoutStartRequest&& from) noexcept
    : StreamoutStartRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutStartRequest& operator=(const StreamoutStartRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutStartRequest& operator=(StreamoutStartRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutStartRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutStartRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutStartRequest*>(
               &_StreamoutStartRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(StreamoutStartRequest& a, StreamoutStartRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutStartRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutStartRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutStartRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutStartRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutStartRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutStartRequest& from) {
    StreamoutStartRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutStartRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutStartRequest";
  }
  protected:
  explicit StreamoutStartRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArgFieldNumber = 1,
  };
  // int32 arg = 1;
  void clear_arg();
  int32_t arg() const;
  void set_arg(int32_t value);
  private:
  int32_t _internal_arg() const;
  void _internal_set_arg(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutStartRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t arg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutStopRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutStopRequest) */ {
 public:
  inline StreamoutStopRequest() : StreamoutStopRequest(nullptr) {}
  ~StreamoutStopRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutStopRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutStopRequest(const StreamoutStopRequest& from);
  StreamoutStopRequest(StreamoutStopRequest&& from) noexcept
    : StreamoutStopRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutStopRequest& operator=(const StreamoutStopRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutStopRequest& operator=(StreamoutStopRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutStopRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutStopRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutStopRequest*>(
               &_StreamoutStopRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(StreamoutStopRequest& a, StreamoutStopRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutStopRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutStopRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutStopRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutStopRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutStopRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutStopRequest& from) {
    StreamoutStopRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutStopRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutStopRequest";
  }
  protected:
  explicit StreamoutStopRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArgFieldNumber = 1,
  };
  // int32 arg = 1;
  void clear_arg();
  int32_t arg() const;
  void set_arg(int32_t value);
  private:
  int32_t _internal_arg() const;
  void _internal_set_arg(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutStopRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t arg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutSetProductIdRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutSetProductIdRequest) */ {
 public:
  inline StreamoutSetProductIdRequest() : StreamoutSetProductIdRequest(nullptr) {}
  ~StreamoutSetProductIdRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutSetProductIdRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutSetProductIdRequest(const StreamoutSetProductIdRequest& from);
  StreamoutSetProductIdRequest(StreamoutSetProductIdRequest&& from) noexcept
    : StreamoutSetProductIdRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutSetProductIdRequest& operator=(const StreamoutSetProductIdRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutSetProductIdRequest& operator=(StreamoutSetProductIdRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutSetProductIdRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutSetProductIdRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutSetProductIdRequest*>(
               &_StreamoutSetProductIdRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(StreamoutSetProductIdRequest& a, StreamoutSetProductIdRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutSetProductIdRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutSetProductIdRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutSetProductIdRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutSetProductIdRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutSetProductIdRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutSetProductIdRequest& from) {
    StreamoutSetProductIdRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutSetProductIdRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutSetProductIdRequest";
  }
  protected:
  explicit StreamoutSetProductIdRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutSetProductIdRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutActionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutActionResponse) */ {
 public:
  inline StreamoutActionResponse() : StreamoutActionResponse(nullptr) {}
  ~StreamoutActionResponse() override;
  explicit PROTOBUF_CONSTEXPR StreamoutActionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutActionResponse(const StreamoutActionResponse& from);
  StreamoutActionResponse(StreamoutActionResponse&& from) noexcept
    : StreamoutActionResponse() {
    *this = ::std::move(from);
  }

  inline StreamoutActionResponse& operator=(const StreamoutActionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutActionResponse& operator=(StreamoutActionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutActionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutActionResponse* internal_default_instance() {
    return reinterpret_cast<const StreamoutActionResponse*>(
               &_StreamoutActionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(StreamoutActionResponse& a, StreamoutActionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutActionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutActionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutActionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutActionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutActionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutActionResponse& from) {
    StreamoutActionResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutActionResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutActionResponse";
  }
  protected:
  explicit StreamoutActionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutActionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutStatusRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutStatusRequest) */ {
 public:
  inline StreamoutStatusRequest() : StreamoutStatusRequest(nullptr) {}
  ~StreamoutStatusRequest() override;
  explicit PROTOBUF_CONSTEXPR StreamoutStatusRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutStatusRequest(const StreamoutStatusRequest& from);
  StreamoutStatusRequest(StreamoutStatusRequest&& from) noexcept
    : StreamoutStatusRequest() {
    *this = ::std::move(from);
  }

  inline StreamoutStatusRequest& operator=(const StreamoutStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutStatusRequest& operator=(StreamoutStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutStatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutStatusRequest* internal_default_instance() {
    return reinterpret_cast<const StreamoutStatusRequest*>(
               &_StreamoutStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(StreamoutStatusRequest& a, StreamoutStatusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutStatusRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutStatusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutStatusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutStatusRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutStatusRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutStatusRequest& from) {
    StreamoutStatusRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutStatusRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutStatusRequest";
  }
  protected:
  explicit StreamoutStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutStatusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// -------------------------------------------------------------------

class StreamoutStatusResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:streamout.v1.StreamoutStatusResponse) */ {
 public:
  inline StreamoutStatusResponse() : StreamoutStatusResponse(nullptr) {}
  ~StreamoutStatusResponse() override;
  explicit PROTOBUF_CONSTEXPR StreamoutStatusResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamoutStatusResponse(const StreamoutStatusResponse& from);
  StreamoutStatusResponse(StreamoutStatusResponse&& from) noexcept
    : StreamoutStatusResponse() {
    *this = ::std::move(from);
  }

  inline StreamoutStatusResponse& operator=(const StreamoutStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamoutStatusResponse& operator=(StreamoutStatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamoutStatusResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamoutStatusResponse* internal_default_instance() {
    return reinterpret_cast<const StreamoutStatusResponse*>(
               &_StreamoutStatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(StreamoutStatusResponse& a, StreamoutStatusResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamoutStatusResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamoutStatusResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamoutStatusResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamoutStatusResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamoutStatusResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamoutStatusResponse& from) {
    StreamoutStatusResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamoutStatusResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "streamout.v1.StreamoutStatusResponse";
  }
  protected:
  explicit StreamoutStatusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusInfoFieldNumber = 3,
    kStreamIdFieldNumber = 1,
    kStatusCodeFieldNumber = 2,
  };
  // string status_info = 3;
  void clear_status_info();
  const std::string& status_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status_info();
  PROTOBUF_NODISCARD std::string* release_status_info();
  void set_allocated_status_info(std::string* status_info);
  private:
  const std::string& _internal_status_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status_info(const std::string& value);
  std::string* _internal_mutable_status_info();
  public:

  // int32 stream_id = 1;
  void clear_stream_id();
  int32_t stream_id() const;
  void set_stream_id(int32_t value);
  private:
  int32_t _internal_stream_id() const;
  void _internal_set_stream_id(int32_t value);
  public:

  // .streamout.v1.StreamStatus status_code = 2;
  void clear_status_code();
  ::streamout::v1::StreamStatus status_code() const;
  void set_status_code(::streamout::v1::StreamStatus value);
  private:
  ::streamout::v1::StreamStatus _internal_status_code() const;
  void _internal_set_status_code(::streamout::v1::StreamStatus value);
  public:

  // @@protoc_insertion_point(class_scope:streamout.v1.StreamoutStatusResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_info_;
    int32_t stream_id_;
    int status_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packagehello_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloRequest

// string name = 1;
inline void HelloRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& HelloRequest::name() const {
  // @@protoc_insertion_point(field_get:streamout.v1.HelloRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HelloRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.HelloRequest.name)
}
inline std::string* HelloRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:streamout.v1.HelloRequest.name)
  return _s;
}
inline const std::string& HelloRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void HelloRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* HelloRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* HelloRequest::release_name() {
  // @@protoc_insertion_point(field_release:streamout.v1.HelloRequest.name)
  return _impl_.name_.Release();
}
inline void HelloRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.HelloRequest.name)
}

// -------------------------------------------------------------------

// HelloReply

// string message = 1;
inline void HelloReply::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& HelloReply::message() const {
  // @@protoc_insertion_point(field_get:streamout.v1.HelloReply.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HelloReply::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.HelloReply.message)
}
inline std::string* HelloReply::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:streamout.v1.HelloReply.message)
  return _s;
}
inline const std::string& HelloReply::_internal_message() const {
  return _impl_.message_.Get();
}
inline void HelloReply::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* HelloReply::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* HelloReply::release_message() {
  // @@protoc_insertion_point(field_release:streamout.v1.HelloReply.message)
  return _impl_.message_.Release();
}
inline void HelloReply::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.HelloReply.message)
}

// -------------------------------------------------------------------

// StreamoutSetPortRequest

// string port = 1;
inline void StreamoutSetPortRequest::clear_port() {
  _impl_.port_.ClearToEmpty();
}
inline const std::string& StreamoutSetPortRequest::port() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutSetPortRequest.port)
  return _internal_port();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamoutSetPortRequest::set_port(ArgT0&& arg0, ArgT... args) {
 
 _impl_.port_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutSetPortRequest.port)
}
inline std::string* StreamoutSetPortRequest::mutable_port() {
  std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:streamout.v1.StreamoutSetPortRequest.port)
  return _s;
}
inline const std::string& StreamoutSetPortRequest::_internal_port() const {
  return _impl_.port_.Get();
}
inline void StreamoutSetPortRequest::_internal_set_port(const std::string& value) {
  
  _impl_.port_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamoutSetPortRequest::_internal_mutable_port() {
  
  return _impl_.port_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamoutSetPortRequest::release_port() {
  // @@protoc_insertion_point(field_release:streamout.v1.StreamoutSetPortRequest.port)
  return _impl_.port_.Release();
}
inline void StreamoutSetPortRequest::set_allocated_port(std::string* port) {
  if (port != nullptr) {
    
  } else {
    
  }
  _impl_.port_.SetAllocated(port, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.StreamoutSetPortRequest.port)
}

// -------------------------------------------------------------------

// StreamoutSetPipelineRequest

// string pipeline = 1;
inline void StreamoutSetPipelineRequest::clear_pipeline() {
  _impl_.pipeline_.ClearToEmpty();
}
inline const std::string& StreamoutSetPipelineRequest::pipeline() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutSetPipelineRequest.pipeline)
  return _internal_pipeline();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamoutSetPipelineRequest::set_pipeline(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pipeline_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutSetPipelineRequest.pipeline)
}
inline std::string* StreamoutSetPipelineRequest::mutable_pipeline() {
  std::string* _s = _internal_mutable_pipeline();
  // @@protoc_insertion_point(field_mutable:streamout.v1.StreamoutSetPipelineRequest.pipeline)
  return _s;
}
inline const std::string& StreamoutSetPipelineRequest::_internal_pipeline() const {
  return _impl_.pipeline_.Get();
}
inline void StreamoutSetPipelineRequest::_internal_set_pipeline(const std::string& value) {
  
  _impl_.pipeline_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamoutSetPipelineRequest::_internal_mutable_pipeline() {
  
  return _impl_.pipeline_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamoutSetPipelineRequest::release_pipeline() {
  // @@protoc_insertion_point(field_release:streamout.v1.StreamoutSetPipelineRequest.pipeline)
  return _impl_.pipeline_.Release();
}
inline void StreamoutSetPipelineRequest::set_allocated_pipeline(std::string* pipeline) {
  if (pipeline != nullptr) {
    
  } else {
    
  }
  _impl_.pipeline_.SetAllocated(pipeline, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pipeline_.IsDefault()) {
    _impl_.pipeline_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.StreamoutSetPipelineRequest.pipeline)
}

// -------------------------------------------------------------------

// StreamoutDebugRequest

// string debug_string = 1;
inline void StreamoutDebugRequest::clear_debug_string() {
  _impl_.debug_string_.ClearToEmpty();
}
inline const std::string& StreamoutDebugRequest::debug_string() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutDebugRequest.debug_string)
  return _internal_debug_string();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamoutDebugRequest::set_debug_string(ArgT0&& arg0, ArgT... args) {
 
 _impl_.debug_string_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutDebugRequest.debug_string)
}
inline std::string* StreamoutDebugRequest::mutable_debug_string() {
  std::string* _s = _internal_mutable_debug_string();
  // @@protoc_insertion_point(field_mutable:streamout.v1.StreamoutDebugRequest.debug_string)
  return _s;
}
inline const std::string& StreamoutDebugRequest::_internal_debug_string() const {
  return _impl_.debug_string_.Get();
}
inline void StreamoutDebugRequest::_internal_set_debug_string(const std::string& value) {
  
  _impl_.debug_string_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamoutDebugRequest::_internal_mutable_debug_string() {
  
  return _impl_.debug_string_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamoutDebugRequest::release_debug_string() {
  // @@protoc_insertion_point(field_release:streamout.v1.StreamoutDebugRequest.debug_string)
  return _impl_.debug_string_.Release();
}
inline void StreamoutDebugRequest::set_allocated_debug_string(std::string* debug_string) {
  if (debug_string != nullptr) {
    
  } else {
    
  }
  _impl_.debug_string_.SetAllocated(debug_string, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.debug_string_.IsDefault()) {
    _impl_.debug_string_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.StreamoutDebugRequest.debug_string)
}

// -------------------------------------------------------------------

// StreamoutStartRequest

// int32 arg = 1;
inline void StreamoutStartRequest::clear_arg() {
  _impl_.arg_ = 0;
}
inline int32_t StreamoutStartRequest::_internal_arg() const {
  return _impl_.arg_;
}
inline int32_t StreamoutStartRequest::arg() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutStartRequest.arg)
  return _internal_arg();
}
inline void StreamoutStartRequest::_internal_set_arg(int32_t value) {
  
  _impl_.arg_ = value;
}
inline void StreamoutStartRequest::set_arg(int32_t value) {
  _internal_set_arg(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutStartRequest.arg)
}

// -------------------------------------------------------------------

// StreamoutStopRequest

// int32 arg = 1;
inline void StreamoutStopRequest::clear_arg() {
  _impl_.arg_ = 0;
}
inline int32_t StreamoutStopRequest::_internal_arg() const {
  return _impl_.arg_;
}
inline int32_t StreamoutStopRequest::arg() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutStopRequest.arg)
  return _internal_arg();
}
inline void StreamoutStopRequest::_internal_set_arg(int32_t value) {
  
  _impl_.arg_ = value;
}
inline void StreamoutStopRequest::set_arg(int32_t value) {
  _internal_set_arg(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutStopRequest.arg)
}

// -------------------------------------------------------------------

// StreamoutSetProductIdRequest

// int32 id = 1;
inline void StreamoutSetProductIdRequest::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t StreamoutSetProductIdRequest::_internal_id() const {
  return _impl_.id_;
}
inline int32_t StreamoutSetProductIdRequest::id() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutSetProductIdRequest.id)
  return _internal_id();
}
inline void StreamoutSetProductIdRequest::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void StreamoutSetProductIdRequest::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutSetProductIdRequest.id)
}

// -------------------------------------------------------------------

// StreamoutActionResponse

// bool success = 1;
inline void StreamoutActionResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool StreamoutActionResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool StreamoutActionResponse::success() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutActionResponse.success)
  return _internal_success();
}
inline void StreamoutActionResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void StreamoutActionResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutActionResponse.success)
}

// string message = 2;
inline void StreamoutActionResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& StreamoutActionResponse::message() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutActionResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamoutActionResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutActionResponse.message)
}
inline std::string* StreamoutActionResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:streamout.v1.StreamoutActionResponse.message)
  return _s;
}
inline const std::string& StreamoutActionResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void StreamoutActionResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamoutActionResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamoutActionResponse::release_message() {
  // @@protoc_insertion_point(field_release:streamout.v1.StreamoutActionResponse.message)
  return _impl_.message_.Release();
}
inline void StreamoutActionResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.StreamoutActionResponse.message)
}

// -------------------------------------------------------------------

// StreamoutStatusRequest

// int32 id = 1;
inline void StreamoutStatusRequest::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t StreamoutStatusRequest::_internal_id() const {
  return _impl_.id_;
}
inline int32_t StreamoutStatusRequest::id() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutStatusRequest.id)
  return _internal_id();
}
inline void StreamoutStatusRequest::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void StreamoutStatusRequest::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutStatusRequest.id)
}

// -------------------------------------------------------------------

// StreamoutStatusResponse

// int32 stream_id = 1;
inline void StreamoutStatusResponse::clear_stream_id() {
  _impl_.stream_id_ = 0;
}
inline int32_t StreamoutStatusResponse::_internal_stream_id() const {
  return _impl_.stream_id_;
}
inline int32_t StreamoutStatusResponse::stream_id() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutStatusResponse.stream_id)
  return _internal_stream_id();
}
inline void StreamoutStatusResponse::_internal_set_stream_id(int32_t value) {
  
  _impl_.stream_id_ = value;
}
inline void StreamoutStatusResponse::set_stream_id(int32_t value) {
  _internal_set_stream_id(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutStatusResponse.stream_id)
}

// .streamout.v1.StreamStatus status_code = 2;
inline void StreamoutStatusResponse::clear_status_code() {
  _impl_.status_code_ = 0;
}
inline ::streamout::v1::StreamStatus StreamoutStatusResponse::_internal_status_code() const {
  return static_cast< ::streamout::v1::StreamStatus >(_impl_.status_code_);
}
inline ::streamout::v1::StreamStatus StreamoutStatusResponse::status_code() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutStatusResponse.status_code)
  return _internal_status_code();
}
inline void StreamoutStatusResponse::_internal_set_status_code(::streamout::v1::StreamStatus value) {
  
  _impl_.status_code_ = value;
}
inline void StreamoutStatusResponse::set_status_code(::streamout::v1::StreamStatus value) {
  _internal_set_status_code(value);
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutStatusResponse.status_code)
}

// string status_info = 3;
inline void StreamoutStatusResponse::clear_status_info() {
  _impl_.status_info_.ClearToEmpty();
}
inline const std::string& StreamoutStatusResponse::status_info() const {
  // @@protoc_insertion_point(field_get:streamout.v1.StreamoutStatusResponse.status_info)
  return _internal_status_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamoutStatusResponse::set_status_info(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_info_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:streamout.v1.StreamoutStatusResponse.status_info)
}
inline std::string* StreamoutStatusResponse::mutable_status_info() {
  std::string* _s = _internal_mutable_status_info();
  // @@protoc_insertion_point(field_mutable:streamout.v1.StreamoutStatusResponse.status_info)
  return _s;
}
inline const std::string& StreamoutStatusResponse::_internal_status_info() const {
  return _impl_.status_info_.Get();
}
inline void StreamoutStatusResponse::_internal_set_status_info(const std::string& value) {
  
  _impl_.status_info_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamoutStatusResponse::_internal_mutable_status_info() {
  
  return _impl_.status_info_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamoutStatusResponse::release_status_info() {
  // @@protoc_insertion_point(field_release:streamout.v1.StreamoutStatusResponse.status_info)
  return _impl_.status_info_.Release();
}
inline void StreamoutStatusResponse::set_allocated_status_info(std::string* status_info) {
  if (status_info != nullptr) {
    
  } else {
    
  }
  _impl_.status_info_.SetAllocated(status_info, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_info_.IsDefault()) {
    _impl_.status_info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:streamout.v1.StreamoutStatusResponse.status_info)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace streamout

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::streamout::v1::StreamStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::streamout::v1::StreamStatus>() {
  return ::streamout::v1::StreamStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_packagehello_2eproto
