// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packagehello.proto
#ifndef GRPC_packagehello_2eproto__INCLUDED
#define GRPC_packagehello_2eproto__INCLUDED

#include "packagehello.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace streamout {
namespace v1 {

class StreamoutService final {
 public:
  static constexpr char const* service_full_name() {
    return "streamout.v1.StreamoutService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // --- Connection Test ---
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::streamout::v1::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    // --- Configuration & Control (Unary) ---
    virtual ::grpc::Status StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::streamout::v1::StreamoutActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutSetPortRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutSetPortRaw(context, request, cq));
    }
    virtual ::grpc::Status StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::streamout::v1::StreamoutActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutSetPipelineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutSetPipelineRaw(context, request, cq));
    }
    virtual ::grpc::Status StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::streamout::v1::StreamoutActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutStartRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutStartRaw(context, request, cq));
    }
    virtual ::grpc::Status StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::streamout::v1::StreamoutActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutStopRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutStopRaw(context, request, cq));
    }
    virtual ::grpc::Status StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::streamout::v1::StreamoutActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutSetProductIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutSetProductIdRaw(context, request, cq));
    }
    // --- Events & Monitoring (Server-Streaming) ---
    std::unique_ptr< ::grpc::ClientReaderInterface< ::streamout::v1::StreamoutStatusResponse>> StreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::streamout::v1::StreamoutStatusResponse>>(StreamoutWatchStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::streamout::v1::StreamoutStatusResponse>> AsyncStreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::streamout::v1::StreamoutStatusResponse>>(AsyncStreamoutWatchStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::streamout::v1::StreamoutStatusResponse>> PrepareAsyncStreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::streamout::v1::StreamoutStatusResponse>>(PrepareAsyncStreamoutWatchStatusRaw(context, request, cq));
    }
    // --- Maintenance ---
    virtual ::grpc::Status StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::streamout::v1::StreamoutActionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutServerDebugRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutServerDebugRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // --- Connection Test ---
      virtual void SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // --- Configuration & Control (Unary) ---
      virtual void StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // --- Events & Monitoring (Server-Streaming) ---
      virtual void StreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest* request, ::grpc::ClientReadReactor< ::streamout::v1::StreamoutStatusResponse>* reactor) = 0;
      // --- Maintenance ---
      virtual void StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutSetPortRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutSetPortRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutSetPipelineRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutSetPipelineRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutStartRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutStartRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutStopRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutStopRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutSetProductIdRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutSetProductIdRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::streamout::v1::StreamoutStatusResponse>* StreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::streamout::v1::StreamoutStatusResponse>* AsyncStreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::streamout::v1::StreamoutStatusResponse>* PrepareAsyncStreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutServerDebugRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutServerDebugRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::streamout::v1::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::streamout::v1::StreamoutActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutSetPortRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutSetPortRaw(context, request, cq));
    }
    ::grpc::Status StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::streamout::v1::StreamoutActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutSetPipelineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutSetPipelineRaw(context, request, cq));
    }
    ::grpc::Status StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::streamout::v1::StreamoutActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutStartRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutStartRaw(context, request, cq));
    }
    ::grpc::Status StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::streamout::v1::StreamoutActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutStopRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutStopRaw(context, request, cq));
    }
    ::grpc::Status StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::streamout::v1::StreamoutActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutSetProductIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutSetProductIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::streamout::v1::StreamoutStatusResponse>> StreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::streamout::v1::StreamoutStatusResponse>>(StreamoutWatchStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>> AsyncStreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>>(AsyncStreamoutWatchStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>> PrepareAsyncStreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>>(PrepareAsyncStreamoutWatchStatusRaw(context, request, cq));
    }
    ::grpc::Status StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::streamout::v1::StreamoutActionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> AsyncStreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(AsyncStreamoutServerDebugRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>> PrepareAsyncStreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>>(PrepareAsyncStreamoutServerDebugRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) override;
      void StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) override;
      void StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) override;
      void StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) override;
      void StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) override;
      void StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest* request, ::grpc::ClientReadReactor< ::streamout::v1::StreamoutStatusResponse>* reactor) override;
      void StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)>) override;
      void StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutSetPortRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutSetPortRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutSetPipelineRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutSetPipelineRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutStartRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutStartRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutStopRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutStopRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutSetProductIdRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutSetProductIdRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::streamout::v1::StreamoutStatusResponse>* StreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request) override;
    ::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>* AsyncStreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>* PrepareAsyncStreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* AsyncStreamoutServerDebugRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* PrepareAsyncStreamoutServerDebugRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutSetPort_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutSetPipeline_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutStart_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutStop_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutSetProductId_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutWatchStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamoutServerDebug_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // --- Connection Test ---
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response);
    // --- Configuration & Control (Unary) ---
    virtual ::grpc::Status StreamoutSetPort(::grpc::ServerContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response);
    virtual ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response);
    virtual ::grpc::Status StreamoutStart(::grpc::ServerContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response);
    virtual ::grpc::Status StreamoutStop(::grpc::ServerContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response);
    virtual ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response);
    // --- Events & Monitoring (Server-Streaming) ---
    virtual ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* context, const ::streamout::v1::StreamoutStatusRequest* request, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* writer);
    // --- Maintenance ---
    virtual ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::streamout::v1::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutSetPort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutSetPort() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamoutSetPort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPort(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutSetPort(::grpc::ServerContext* context, ::streamout::v1::StreamoutSetPortRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::StreamoutActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutSetPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutSetPipeline() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamoutSetPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutSetPipeline(::grpc::ServerContext* context, ::streamout::v1::StreamoutSetPipelineRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::StreamoutActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutStart() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_StreamoutStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStart(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutStart(::grpc::ServerContext* context, ::streamout::v1::StreamoutStartRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::StreamoutActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutStop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutStop() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_StreamoutStop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStop(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutStop(::grpc::ServerContext* context, ::streamout::v1::StreamoutStopRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::StreamoutActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutSetProductId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutSetProductId() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_StreamoutSetProductId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutSetProductId(::grpc::ServerContext* context, ::streamout::v1::StreamoutSetProductIdRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::StreamoutActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutWatchStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutWatchStatus() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_StreamoutWatchStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutWatchStatus(::grpc::ServerContext* context, ::streamout::v1::StreamoutStatusRequest* request, ::grpc::ServerAsyncWriter< ::streamout::v1::StreamoutStatusResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamoutServerDebug : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamoutServerDebug() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_StreamoutServerDebug() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutServerDebug(::grpc::ServerContext* context, ::streamout::v1::StreamoutDebugRequest* request, ::grpc::ServerAsyncResponseWriter< ::streamout::v1::StreamoutActionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_StreamoutSetPort<WithAsyncMethod_StreamoutSetPipeline<WithAsyncMethod_StreamoutStart<WithAsyncMethod_StreamoutStop<WithAsyncMethod_StreamoutSetProductId<WithAsyncMethod_StreamoutWatchStatus<WithAsyncMethod_StreamoutServerDebug<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutSetPort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutSetPort() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response) { return this->StreamoutSetPort(context, request, response); }));}
    void SetMessageAllocatorFor_StreamoutSetPort(
        ::grpc::MessageAllocator< ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamoutSetPort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPort(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutSetPort(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutSetPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutSetPipeline() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response) { return this->StreamoutSetPipeline(context, request, response); }));}
    void SetMessageAllocatorFor_StreamoutSetPipeline(
        ::grpc::MessageAllocator< ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamoutSetPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutSetPipeline(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutStart() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response) { return this->StreamoutStart(context, request, response); }));}
    void SetMessageAllocatorFor_StreamoutStart(
        ::grpc::MessageAllocator< ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamoutStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStart(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutStart(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutStop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutStop() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response) { return this->StreamoutStop(context, request, response); }));}
    void SetMessageAllocatorFor_StreamoutStop(
        ::grpc::MessageAllocator< ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamoutStop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStop(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutStop(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutSetProductId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutSetProductId() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response) { return this->StreamoutSetProductId(context, request, response); }));}
    void SetMessageAllocatorFor_StreamoutSetProductId(
        ::grpc::MessageAllocator< ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamoutSetProductId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutSetProductId(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutWatchStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutWatchStatus() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::streamout::v1::StreamoutStatusRequest, ::streamout::v1::StreamoutStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutStatusRequest* request) { return this->StreamoutWatchStatus(context, request); }));
    }
    ~WithCallbackMethod_StreamoutWatchStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::streamout::v1::StreamoutStatusResponse>* StreamoutWatchStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamoutServerDebug : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamoutServerDebug() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response) { return this->StreamoutServerDebug(context, request, response); }));}
    void SetMessageAllocatorFor_StreamoutServerDebug(
        ::grpc::MessageAllocator< ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StreamoutServerDebug() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutServerDebug(
      ::grpc::CallbackServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_StreamoutSetPort<WithCallbackMethod_StreamoutSetPipeline<WithCallbackMethod_StreamoutStart<WithCallbackMethod_StreamoutStop<WithCallbackMethod_StreamoutSetProductId<WithCallbackMethod_StreamoutWatchStatus<WithCallbackMethod_StreamoutServerDebug<Service > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutSetPort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutSetPort() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamoutSetPort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPort(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutSetPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutSetPipeline() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamoutSetPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutStart() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_StreamoutStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStart(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutStop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutStop() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_StreamoutStop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStop(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutSetProductId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutSetProductId() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_StreamoutSetProductId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutWatchStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutWatchStatus() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_StreamoutWatchStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamoutServerDebug : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamoutServerDebug() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_StreamoutServerDebug() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutSetPort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutSetPort() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamoutSetPort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPort(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutSetPort(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutSetPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutSetPipeline() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamoutSetPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutSetPipeline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutStart() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_StreamoutStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStart(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutStart(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutStop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutStop() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_StreamoutStop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStop(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutStop(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutSetProductId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutSetProductId() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_StreamoutSetProductId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutSetProductId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutWatchStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutWatchStatus() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_StreamoutWatchStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutWatchStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamoutServerDebug : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamoutServerDebug() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_StreamoutServerDebug() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamoutServerDebug(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutSetPort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutSetPort() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamoutSetPort(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamoutSetPort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPort(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutSetPort(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutSetPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutSetPipeline() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamoutSetPipeline(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamoutSetPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutSetPipeline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutStart() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamoutStart(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamoutStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStart(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutStart(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutStop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutStop() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamoutStop(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamoutStop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutStop(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutStop(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutSetProductId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutSetProductId() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamoutSetProductId(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamoutSetProductId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutSetProductId(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutWatchStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutWatchStatus() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamoutWatchStatus(context, request); }));
    }
    ~WithRawCallbackMethod_StreamoutWatchStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamoutWatchStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamoutServerDebug : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamoutServerDebug() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StreamoutServerDebug(context, request, response); }));
    }
    ~WithRawCallbackMethod_StreamoutServerDebug() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StreamoutServerDebug(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::streamout::v1::HelloRequest* /*request*/, ::streamout::v1::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::HelloRequest,::streamout::v1::HelloReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamoutSetPort : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamoutSetPort() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse>* streamer) {
                       return this->StreamedStreamoutSetPort(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamoutSetPort() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutSetPort(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPortRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamoutSetPort(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::StreamoutSetPortRequest,::streamout::v1::StreamoutActionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamoutSetPipeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamoutSetPipeline() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse>* streamer) {
                       return this->StreamedStreamoutSetPipeline(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamoutSetPipeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutSetPipeline(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetPipelineRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamoutSetPipeline(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::StreamoutSetPipelineRequest,::streamout::v1::StreamoutActionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamoutStart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamoutStart() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse>* streamer) {
                       return this->StreamedStreamoutStart(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamoutStart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutStart(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStartRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamoutStart(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::StreamoutStartRequest,::streamout::v1::StreamoutActionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamoutStop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamoutStop() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse>* streamer) {
                       return this->StreamedStreamoutStop(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamoutStop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutStop(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStopRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamoutStop(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::StreamoutStopRequest,::streamout::v1::StreamoutActionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamoutSetProductId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamoutSetProductId() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse>* streamer) {
                       return this->StreamedStreamoutSetProductId(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamoutSetProductId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutSetProductId(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutSetProductIdRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamoutSetProductId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::StreamoutSetProductIdRequest,::streamout::v1::StreamoutActionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StreamoutServerDebug : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StreamoutServerDebug() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse>* streamer) {
                       return this->StreamedStreamoutServerDebug(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StreamoutServerDebug() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutServerDebug(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutDebugRequest* /*request*/, ::streamout::v1::StreamoutActionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStreamoutServerDebug(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::streamout::v1::StreamoutDebugRequest,::streamout::v1::StreamoutActionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_StreamoutSetPort<WithStreamedUnaryMethod_StreamoutSetPipeline<WithStreamedUnaryMethod_StreamoutStart<WithStreamedUnaryMethod_StreamoutStop<WithStreamedUnaryMethod_StreamoutSetProductId<WithStreamedUnaryMethod_StreamoutServerDebug<Service > > > > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamoutWatchStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamoutWatchStatus() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::streamout::v1::StreamoutStatusRequest, ::streamout::v1::StreamoutStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::streamout::v1::StreamoutStatusRequest, ::streamout::v1::StreamoutStatusResponse>* streamer) {
                       return this->StreamedStreamoutWatchStatus(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamoutWatchStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamoutWatchStatus(::grpc::ServerContext* /*context*/, const ::streamout::v1::StreamoutStatusRequest* /*request*/, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamoutWatchStatus(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::streamout::v1::StreamoutStatusRequest,::streamout::v1::StreamoutStatusResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamoutWatchStatus<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_StreamoutSetPort<WithStreamedUnaryMethod_StreamoutSetPipeline<WithStreamedUnaryMethod_StreamoutStart<WithStreamedUnaryMethod_StreamoutStop<WithStreamedUnaryMethod_StreamoutSetProductId<WithSplitStreamingMethod_StreamoutWatchStatus<WithStreamedUnaryMethod_StreamoutServerDebug<Service > > > > > > > > StreamedService;
};

}  // namespace v1
}  // namespace streamout


#endif  // GRPC_packagehello_2eproto__INCLUDED
