// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packagehello.proto

#include "packagehello.pb.h"
#include "packagehello.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace streamout {
namespace v1 {

static const char* StreamoutService_method_names[] = {
  "/streamout.v1.StreamoutService/SayHello",
  "/streamout.v1.StreamoutService/StreamoutSetPort",
  "/streamout.v1.StreamoutService/StreamoutSetPipeline",
  "/streamout.v1.StreamoutService/StreamoutStart",
  "/streamout.v1.StreamoutService/StreamoutStop",
  "/streamout.v1.StreamoutService/StreamoutSetProductId",
  "/streamout.v1.StreamoutService/StreamoutWatchStatus",
  "/streamout.v1.StreamoutService/StreamoutServerDebug",
};

std::unique_ptr< StreamoutService::Stub> StreamoutService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StreamoutService::Stub> stub(new StreamoutService::Stub(channel, options));
  return stub;
}

StreamoutService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(StreamoutService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamoutSetPort_(StreamoutService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamoutSetPipeline_(StreamoutService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamoutStart_(StreamoutService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamoutStop_(StreamoutService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamoutSetProductId_(StreamoutService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamoutWatchStatus_(StreamoutService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_StreamoutServerDebug_(StreamoutService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StreamoutService::Stub::SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::streamout::v1::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void StreamoutService::Stub::async::SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::SayHello(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>* StreamoutService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::HelloReply, ::streamout::v1::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::HelloReply>* StreamoutService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::streamout::v1::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StreamoutService::Stub::StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::streamout::v1::StreamoutActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StreamoutSetPort_, context, request, response);
}

void StreamoutService::Stub::async::StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutSetPort_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::StreamoutSetPort(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutSetPort_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::PrepareAsyncStreamoutSetPortRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::StreamoutActionResponse, ::streamout::v1::StreamoutSetPortRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StreamoutSetPort_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::AsyncStreamoutSetPortRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPortRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStreamoutSetPortRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StreamoutService::Stub::StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::streamout::v1::StreamoutActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StreamoutSetPipeline_, context, request, response);
}

void StreamoutService::Stub::async::StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutSetPipeline_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::StreamoutSetPipeline(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutSetPipeline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::PrepareAsyncStreamoutSetPipelineRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::StreamoutActionResponse, ::streamout::v1::StreamoutSetPipelineRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StreamoutSetPipeline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::AsyncStreamoutSetPipelineRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetPipelineRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStreamoutSetPipelineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StreamoutService::Stub::StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::streamout::v1::StreamoutActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StreamoutStart_, context, request, response);
}

void StreamoutService::Stub::async::StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutStart_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::StreamoutStart(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::PrepareAsyncStreamoutStartRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::StreamoutActionResponse, ::streamout::v1::StreamoutStartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StreamoutStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::AsyncStreamoutStartRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStreamoutStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StreamoutService::Stub::StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::streamout::v1::StreamoutActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StreamoutStop_, context, request, response);
}

void StreamoutService::Stub::async::StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutStop_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::StreamoutStop(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::PrepareAsyncStreamoutStopRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::StreamoutActionResponse, ::streamout::v1::StreamoutStopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StreamoutStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::AsyncStreamoutStopRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStreamoutStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StreamoutService::Stub::StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::streamout::v1::StreamoutActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StreamoutSetProductId_, context, request, response);
}

void StreamoutService::Stub::async::StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutSetProductId_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::StreamoutSetProductId(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutSetProductId_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::PrepareAsyncStreamoutSetProductIdRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::StreamoutActionResponse, ::streamout::v1::StreamoutSetProductIdRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StreamoutSetProductId_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::AsyncStreamoutSetProductIdRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutSetProductIdRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStreamoutSetProductIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::streamout::v1::StreamoutStatusResponse>* StreamoutService::Stub::StreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::streamout::v1::StreamoutStatusResponse>::Create(channel_.get(), rpcmethod_StreamoutWatchStatus_, context, request);
}

void StreamoutService::Stub::async::StreamoutWatchStatus(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest* request, ::grpc::ClientReadReactor< ::streamout::v1::StreamoutStatusResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::streamout::v1::StreamoutStatusResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamoutWatchStatus_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>* StreamoutService::Stub::AsyncStreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::streamout::v1::StreamoutStatusResponse>::Create(channel_.get(), cq, rpcmethod_StreamoutWatchStatus_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::streamout::v1::StreamoutStatusResponse>* StreamoutService::Stub::PrepareAsyncStreamoutWatchStatusRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::streamout::v1::StreamoutStatusResponse>::Create(channel_.get(), cq, rpcmethod_StreamoutWatchStatus_, context, request, false, nullptr);
}

::grpc::Status StreamoutService::Stub::StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::streamout::v1::StreamoutActionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StreamoutServerDebug_, context, request, response);
}

void StreamoutService::Stub::async::StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutServerDebug_, context, request, response, std::move(f));
}

void StreamoutService::Stub::async::StreamoutServerDebug(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StreamoutServerDebug_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::PrepareAsyncStreamoutServerDebugRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::streamout::v1::StreamoutActionResponse, ::streamout::v1::StreamoutDebugRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StreamoutServerDebug_, context, request);
}

::grpc::ClientAsyncResponseReader< ::streamout::v1::StreamoutActionResponse>* StreamoutService::Stub::AsyncStreamoutServerDebugRaw(::grpc::ClientContext* context, const ::streamout::v1::StreamoutDebugRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStreamoutServerDebugRaw(context, request, cq);
  result->StartCall();
  return result;
}

StreamoutService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::HelloRequest, ::streamout::v1::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::HelloRequest* req,
             ::streamout::v1::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::StreamoutSetPortRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutSetPortRequest* req,
             ::streamout::v1::StreamoutActionResponse* resp) {
               return service->StreamoutSetPort(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::StreamoutSetPipelineRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutSetPipelineRequest* req,
             ::streamout::v1::StreamoutActionResponse* resp) {
               return service->StreamoutSetPipeline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::StreamoutStartRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutStartRequest* req,
             ::streamout::v1::StreamoutActionResponse* resp) {
               return service->StreamoutStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::StreamoutStopRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutStopRequest* req,
             ::streamout::v1::StreamoutActionResponse* resp) {
               return service->StreamoutStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::StreamoutSetProductIdRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutSetProductIdRequest* req,
             ::streamout::v1::StreamoutActionResponse* resp) {
               return service->StreamoutSetProductId(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StreamoutService::Service, ::streamout::v1::StreamoutStatusRequest, ::streamout::v1::StreamoutStatusResponse>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutStatusRequest* req,
             ::grpc::ServerWriter<::streamout::v1::StreamoutStatusResponse>* writer) {
               return service->StreamoutWatchStatus(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamoutService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamoutService::Service, ::streamout::v1::StreamoutDebugRequest, ::streamout::v1::StreamoutActionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamoutService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::streamout::v1::StreamoutDebugRequest* req,
             ::streamout::v1::StreamoutActionResponse* resp) {
               return service->StreamoutServerDebug(ctx, req, resp);
             }, this)));
}

StreamoutService::Service::~Service() {
}

::grpc::Status StreamoutService::Service::SayHello(::grpc::ServerContext* context, const ::streamout::v1::HelloRequest* request, ::streamout::v1::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutSetPort(::grpc::ServerContext* context, const ::streamout::v1::StreamoutSetPortRequest* request, ::streamout::v1::StreamoutActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutSetPipeline(::grpc::ServerContext* context, const ::streamout::v1::StreamoutSetPipelineRequest* request, ::streamout::v1::StreamoutActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutStart(::grpc::ServerContext* context, const ::streamout::v1::StreamoutStartRequest* request, ::streamout::v1::StreamoutActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutStop(::grpc::ServerContext* context, const ::streamout::v1::StreamoutStopRequest* request, ::streamout::v1::StreamoutActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutSetProductId(::grpc::ServerContext* context, const ::streamout::v1::StreamoutSetProductIdRequest* request, ::streamout::v1::StreamoutActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutWatchStatus(::grpc::ServerContext* context, const ::streamout::v1::StreamoutStatusRequest* request, ::grpc::ServerWriter< ::streamout::v1::StreamoutStatusResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamoutService::Service::StreamoutServerDebug(::grpc::ServerContext* context, const ::streamout::v1::StreamoutDebugRequest* request, ::streamout::v1::StreamoutActionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace streamout
}  // namespace v1

